# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: riuson.rssreader::lang.backend_channel.record_name_channel

# Model Form Field configuration
form: $/riuson/rssreader/models/channel/fields.yaml

# Model Class name
modelClass: Riuson\RssReader\Models\Channel

# Default redirect location
defaultRedirect: riuson/rssreader/channels

# Create page
create:
    title: riuson.rssreader::lang.backend_channel.create_channel
    redirect: riuson/rssreader/channels/update/:id
    redirectClose: riuson/rssreader/channels

# Update page
update:
    title: riuson.rssreader::lang.backend_channel.edit_channel
    redirect: riuson/rssreader/channels
    redirectClose: riuson/rssreader/channels

# Preview page
preview:
    title: riuson.rssreader::lang.backend_channel.preview_channel